package config

import (
	"fmt"
	"os"
)

// InitFile writes a default .envsync.toml to path.
// It returns an error if the file already exists.
func InitFile(path string) error {
	if path == "" {
		path = DefaultConfigFile
	}

	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("config: %q already exists", path)
	}

	content := `# envsync configuration
# Generated by envsync init

[store]
# Path to the encrypted secret store file or directory.
# Commit this path (but NOT the store itself) to version control.
path = ".envsync-store"

[env]
# Path to the .env file managed by envsync.
file = ".env"
`
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("config: writing %q: %w", path, err)
	}
	return nil
}
